- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name: create vprofile VPC
      ec2_vpc_net:
        name: "{{vprofile VPC}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        state: "{{state}}"
        tags:
          - key: "dns_support"
            value: "yes"
          - key: "dns_hostnames"
            value: "yes"
        tenancy: default
      state: "{{state}}"
      register: vpcout