- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup

    - name:
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        tags:
          - key: "dns_support"
            value: "yes"
          - key: "dns_hostnames"
            value: "yes"
        tenancy: default
      state: "{{state}}"
      register: vpcout